/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_serverFn/createRecurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Neuen Dauerauftrag anlegen
         * @description Erfordert eine angemeldete Sitzung (`requireSupabaseAuth`); Rollenrechte
         *     werden zusätzlich per RLS erzwungen.
         */
        post: operations["createRecurring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_serverFn/updateRecurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bestehenden Dauerauftrag ändern
         * @description Teil-Update. Pflichtfeldprüfungen laufen nur für Felder, die im Patch
         *     enthalten sind. Field-Paths werden **ohne** `values.`-Präfix gemeldet
         *     (aus `values.patient` wird `patient`).
         */
        post: operations["updateRecurring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Ein einzelner Feldfehler. */
        FeldFehler: {
            /**
             * @description Punkt-Pfad des Feldes, immer ohne `values.`-Präfix. Ist kein Pfad
             *     ermittelbar, lautet der Wert `formular`. Pro Pfad erscheint
             *     höchstens ein Eintrag (erster Fehler gewinnt).
             * @example patient
             * @example pickup.postalCode
             * @example wochentage
             * @example formular
             */
            path: string;
            /**
             * @description Deutsches Anzeige-Label aus `DAUERAUFTRAG_FELD_LABEL`
             *     (`src/lib/recurring-validation.ts`), Fallback ist `path`.
             * @example Pickup – PLZ
             */
            label: string;
            /**
             * @description Endnutzer-taugliche Meldung.
             * @example Bitte den Namen des Patienten angeben.
             */
            message: string;
        };
        /** @description JSON-Teil hinter dem Marker. */
        FeldFehlerListe: {
            fields: components["schemas"]["FeldFehler"][];
        };
        /**
         * @description Fehlerobjekt des RPC-Transports. Aufbau der `message`:
         *     `<lesbarer Text><MARKER><JSON>` mit
         *     `<MARKER>` = `__GHASI_FELDFEHLER__` und `<JSON>` gemäß `FeldFehlerListe`.
         *     Dekodieren mit `dekodiereFeldFehler`, `feldFehlerMap` und
         *     `lesbarerFehlerText` aus `@/lib/recurring-validation`.
         */
        FeldFehlerKodierung: {
            message: string;
        } & {
            [key: string]: unknown;
        };
        Adresse: {
            street?: string;
            houseNumber?: string;
            postalCode?: string;
            city?: string;
            country?: string;
            additionalInfo?: string;
        };
        /**
         * @description Strenges Schema (`.strict()`) – unbekannte Felder werden abgelehnt und
         *     als Feldfehler gemeldet.
         */
        RecurringFields: {
            kennung?: string;
            patient: string;
            /** Format: uuid */
            patientId?: string | null;
            /** Format: uuid */
            insurerId?: string | null;
            abholort?: string;
            zielort?: string;
            pickup?: components["schemas"]["Adresse"];
            destination?: components["schemas"]["Adresse"];
            terminzeit: string;
            rueckfahrt?: boolean;
            rueckfahrtzeit?: string | null;
            /** @enum {string} */
            mobilitaet?: "gehfaehig" | "rollstuhl" | "tragestuhl" | "liegend";
            begleitperson?: boolean;
            verordnungErforderlich?: boolean;
            kostentraeger?: string;
            krankenkasse?: string;
            bevorzugterFahrer?: string | null;
            bevorzugtesFahrzeug?: string | null;
            /** Format: uuid */
            bevorzugterFahrerId?: string | null;
            /** Format: uuid */
            bevorzugtesFahrzeugId?: string | null;
            notiz?: string;
            medizinischeNotiz?: string;
            /** @enum {string} */
            kategorie?: "dialyse" | "pflegeheim" | "krankenhaus" | "sonstige";
            /** @enum {string} */
            rhythmus?: "taeglich" | "woechentlich";
            /** @description 0 = Sonntag … 6 = Samstag (wie `Date.getDay()`). */
            wochentage?: number[];
            startDatum?: string;
            endDatum?: string | null;
            pauseVon?: string | null;
            pauseBis?: string | null;
            pausiert?: boolean;
            feiertageUeberspringen?: boolean;
            uebersprungeneTermine?: string[];
            generierteTermine?: string[];
        };
        CreateRecurringRequest: {
            data: components["schemas"]["RecurringFields"];
        };
        UpdateRecurringRequest: {
            data: {
                /** Format: uuid */
                id: string;
                /**
                 * @description Teilmenge der Felder; mindestens ein Feld ist erforderlich,
                 *     sonst Feldfehler auf `values`
                 *     („Keine Änderungen übergeben.“).
                 */
                values: components["schemas"]["RecurringFields"];
            };
        };
        /**
         * @description Gespeicherter Dauerauftrag (`Dauerauftrag` aus `@/lib/dauerauftraege`).
         *     Enthält alle Felder aus `RecurringFields` plus Systemfelder.
         */
        Dauerauftrag: {
            /** Format: uuid */
            id?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /**
         * @description Validierungsfehler. `message` enthält den lesbaren Text, den Marker
         *     `__GHASI_FELDFEHLER__` und danach das JSON `{"fields":[...]}`.
         */
        FeldfehlerAntwort: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FeldFehlerKodierung"];
            };
        };
        /** @description Keine gültige Sitzung. */
        NichtAngemeldet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /**
         * @description Fachlicher oder technischer Fehler **ohne** Feldliste, z. B. wenn
         *     `patientId`, `insurerId`, `bevorzugterFahrerId` oder
         *     `bevorzugtesFahrzeugId` nicht existieren, oder bei Datenbankfehlern.
         */
        Serverfehler: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Patient nicht gefunden. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringRequest"];
            };
        };
        responses: {
            /** @description Dauerauftrag angelegt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dauerauftrag"];
                };
            };
            400: components["responses"]["FeldfehlerAntwort"];
            401: components["responses"]["NichtAngemeldet"];
            500: components["responses"]["Serverfehler"];
        };
    };
    updateRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecurringRequest"];
            };
        };
        responses: {
            /** @description Dauerauftrag geändert */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dauerauftrag"];
                };
            };
            400: components["responses"]["FeldfehlerAntwort"];
            401: components["responses"]["NichtAngemeldet"];
            500: components["responses"]["Serverfehler"];
        };
    };
}
