/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KiAssistentRouteImport } from './routes/ki-assistent'
import { Route as IndexRouteImport } from './routes/index'

const KiAssistentRoute = KiAssistentRouteImport.update({
  id: '/ki-assistent',
  path: '/ki-assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ki-assistent': typeof KiAssistentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ki-assistent': typeof KiAssistentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ki-assistent': typeof KiAssistentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ki-assistent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ki-assistent'
  id: '__root__' | '/' | '/ki-assistent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KiAssistentRoute: typeof KiAssistentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ki-assistent': {
      id: '/ki-assistent'
      path: '/ki-assistent'
      fullPath: '/ki-assistent'
      preLoaderRoute: typeof KiAssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KiAssistentRoute: KiAssistentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
