/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WartungRouteImport } from './routes/wartung'
import { Route as WarnungenRouteImport } from './routes/warnungen'
import { Route as VersicherungenRouteImport } from './routes/versicherungen'
import { Route as VerbindungenRouteImport } from './routes/verbindungen'
import { Route as TourenplanungRouteImport } from './routes/tourenplanung'
import { Route as TelefonRouteImport } from './routes/telefon'
import { Route as StatistikenRouteImport } from './routes/statistiken'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechnungenRouteImport } from './routes/rechnungen'
import { Route as PrognosenRouteImport } from './routes/prognosen'
import { Route as PosteingangRouteImport } from './routes/posteingang'
import { Route as PflegeheimeRouteImport } from './routes/pflegeheime'
import { Route as PatientenRouteImport } from './routes/patienten'
import { Route as LiveGpsRouteImport } from './routes/live-gps'
import { Route as LeasingRouteImport } from './routes/leasing'
import { Route as KundenRouteImport } from './routes/kunden'
import { Route as KrankenhaeuserRouteImport } from './routes/krankenhaeuser'
import { Route as KiAssistentRouteImport } from './routes/ki-assistent'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FahrzeugeRouteImport } from './routes/fahrzeuge'
import { Route as FahrerRouteImport } from './routes/fahrer'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as DokumenteRouteImport } from './routes/dokumente'
import { Route as DialysezentrenRouteImport } from './routes/dialysezentren'
import { Route as ControlCenterRouteImport } from './routes/control-center'
import { Route as BuchhaltungRouteImport } from './routes/buchhaltung'
import { Route as BerichteRouteImport } from './routes/berichte'
import { Route as AuftraegeRouteImport } from './routes/auftraege'
import { Route as AktivitaetenRouteImport } from './routes/aktivitaeten'
import { Route as AktionsCenterRouteImport } from './routes/aktions-center'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KiAssistentIndexRouteImport } from './routes/ki-assistent.index'
import { Route as KiAssistentThreadIdRouteImport } from './routes/ki-assistent.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WartungRoute = WartungRouteImport.update({
  id: '/wartung',
  path: '/wartung',
  getParentRoute: () => rootRouteImport,
} as any)
const WarnungenRoute = WarnungenRouteImport.update({
  id: '/warnungen',
  path: '/warnungen',
  getParentRoute: () => rootRouteImport,
} as any)
const VersicherungenRoute = VersicherungenRouteImport.update({
  id: '/versicherungen',
  path: '/versicherungen',
  getParentRoute: () => rootRouteImport,
} as any)
const VerbindungenRoute = VerbindungenRouteImport.update({
  id: '/verbindungen',
  path: '/verbindungen',
  getParentRoute: () => rootRouteImport,
} as any)
const TourenplanungRoute = TourenplanungRouteImport.update({
  id: '/tourenplanung',
  path: '/tourenplanung',
  getParentRoute: () => rootRouteImport,
} as any)
const TelefonRoute = TelefonRouteImport.update({
  id: '/telefon',
  path: '/telefon',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikenRoute = StatistikenRouteImport.update({
  id: '/statistiken',
  path: '/statistiken',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnungenRoute = RechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrognosenRoute = PrognosenRouteImport.update({
  id: '/prognosen',
  path: '/prognosen',
  getParentRoute: () => rootRouteImport,
} as any)
const PosteingangRoute = PosteingangRouteImport.update({
  id: '/posteingang',
  path: '/posteingang',
  getParentRoute: () => rootRouteImport,
} as any)
const PflegeheimeRoute = PflegeheimeRouteImport.update({
  id: '/pflegeheime',
  path: '/pflegeheime',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientenRoute = PatientenRouteImport.update({
  id: '/patienten',
  path: '/patienten',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveGpsRoute = LiveGpsRouteImport.update({
  id: '/live-gps',
  path: '/live-gps',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasingRoute = LeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenRoute = KundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => rootRouteImport,
} as any)
const KrankenhaeuserRoute = KrankenhaeuserRouteImport.update({
  id: '/krankenhaeuser',
  path: '/krankenhaeuser',
  getParentRoute: () => rootRouteImport,
} as any)
const KiAssistentRoute = KiAssistentRouteImport.update({
  id: '/ki-assistent',
  path: '/ki-assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugeRoute = FahrzeugeRouteImport.update({
  id: '/fahrzeuge',
  path: '/fahrzeuge',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrerRoute = FahrerRouteImport.update({
  id: '/fahrer',
  path: '/fahrer',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenteRoute = DokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const DialysezentrenRoute = DialysezentrenRouteImport.update({
  id: '/dialysezentren',
  path: '/dialysezentren',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRoute = ControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchhaltungRoute = BuchhaltungRouteImport.update({
  id: '/buchhaltung',
  path: '/buchhaltung',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichteRoute = BerichteRouteImport.update({
  id: '/berichte',
  path: '/berichte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuftraegeRoute = AuftraegeRouteImport.update({
  id: '/auftraege',
  path: '/auftraege',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitaetenRoute = AktivitaetenRouteImport.update({
  id: '/aktivitaeten',
  path: '/aktivitaeten',
  getParentRoute: () => rootRouteImport,
} as any)
const AktionsCenterRoute = AktionsCenterRouteImport.update({
  id: '/aktions-center',
  path: '/aktions-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KiAssistentIndexRoute = KiAssistentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KiAssistentRoute,
} as any)
const KiAssistentThreadIdRoute = KiAssistentThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => KiAssistentRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/aktions-center': typeof AktionsCenterRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/auftraege': typeof AuftraegeRoute
  '/berichte': typeof BerichteRoute
  '/buchhaltung': typeof BuchhaltungRoute
  '/control-center': typeof ControlCenterRoute
  '/dialysezentren': typeof DialysezentrenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fahrer': typeof FahrerRoute
  '/fahrzeuge': typeof FahrzeugeRoute
  '/insights': typeof InsightsRoute
  '/ki-assistent': typeof KiAssistentRouteWithChildren
  '/krankenhaeuser': typeof KrankenhaeuserRoute
  '/kunden': typeof KundenRoute
  '/leasing': typeof LeasingRoute
  '/live-gps': typeof LiveGpsRoute
  '/patienten': typeof PatientenRoute
  '/pflegeheime': typeof PflegeheimeRoute
  '/posteingang': typeof PosteingangRoute
  '/prognosen': typeof PrognosenRoute
  '/rechnungen': typeof RechnungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiken': typeof StatistikenRoute
  '/telefon': typeof TelefonRoute
  '/tourenplanung': typeof TourenplanungRoute
  '/verbindungen': typeof VerbindungenRoute
  '/versicherungen': typeof VersicherungenRoute
  '/warnungen': typeof WarnungenRoute
  '/wartung': typeof WartungRoute
  '/api/chat': typeof ApiChatRoute
  '/ki-assistent/$threadId': typeof KiAssistentThreadIdRoute
  '/ki-assistent/': typeof KiAssistentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/aktions-center': typeof AktionsCenterRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/auftraege': typeof AuftraegeRoute
  '/berichte': typeof BerichteRoute
  '/buchhaltung': typeof BuchhaltungRoute
  '/control-center': typeof ControlCenterRoute
  '/dialysezentren': typeof DialysezentrenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fahrer': typeof FahrerRoute
  '/fahrzeuge': typeof FahrzeugeRoute
  '/insights': typeof InsightsRoute
  '/krankenhaeuser': typeof KrankenhaeuserRoute
  '/kunden': typeof KundenRoute
  '/leasing': typeof LeasingRoute
  '/live-gps': typeof LiveGpsRoute
  '/patienten': typeof PatientenRoute
  '/pflegeheime': typeof PflegeheimeRoute
  '/posteingang': typeof PosteingangRoute
  '/prognosen': typeof PrognosenRoute
  '/rechnungen': typeof RechnungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiken': typeof StatistikenRoute
  '/telefon': typeof TelefonRoute
  '/tourenplanung': typeof TourenplanungRoute
  '/verbindungen': typeof VerbindungenRoute
  '/versicherungen': typeof VersicherungenRoute
  '/warnungen': typeof WarnungenRoute
  '/wartung': typeof WartungRoute
  '/api/chat': typeof ApiChatRoute
  '/ki-assistent/$threadId': typeof KiAssistentThreadIdRoute
  '/ki-assistent': typeof KiAssistentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/aktions-center': typeof AktionsCenterRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/auftraege': typeof AuftraegeRoute
  '/berichte': typeof BerichteRoute
  '/buchhaltung': typeof BuchhaltungRoute
  '/control-center': typeof ControlCenterRoute
  '/dialysezentren': typeof DialysezentrenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fahrer': typeof FahrerRoute
  '/fahrzeuge': typeof FahrzeugeRoute
  '/insights': typeof InsightsRoute
  '/ki-assistent': typeof KiAssistentRouteWithChildren
  '/krankenhaeuser': typeof KrankenhaeuserRoute
  '/kunden': typeof KundenRoute
  '/leasing': typeof LeasingRoute
  '/live-gps': typeof LiveGpsRoute
  '/patienten': typeof PatientenRoute
  '/pflegeheime': typeof PflegeheimeRoute
  '/posteingang': typeof PosteingangRoute
  '/prognosen': typeof PrognosenRoute
  '/rechnungen': typeof RechnungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistiken': typeof StatistikenRoute
  '/telefon': typeof TelefonRoute
  '/tourenplanung': typeof TourenplanungRoute
  '/verbindungen': typeof VerbindungenRoute
  '/versicherungen': typeof VersicherungenRoute
  '/warnungen': typeof WarnungenRoute
  '/wartung': typeof WartungRoute
  '/api/chat': typeof ApiChatRoute
  '/ki-assistent/$threadId': typeof KiAssistentThreadIdRoute
  '/ki-assistent/': typeof KiAssistentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/aktions-center'
    | '/aktivitaeten'
    | '/auftraege'
    | '/berichte'
    | '/buchhaltung'
    | '/control-center'
    | '/dialysezentren'
    | '/dokumente'
    | '/einstellungen'
    | '/fahrer'
    | '/fahrzeuge'
    | '/insights'
    | '/ki-assistent'
    | '/krankenhaeuser'
    | '/kunden'
    | '/leasing'
    | '/live-gps'
    | '/patienten'
    | '/pflegeheime'
    | '/posteingang'
    | '/prognosen'
    | '/rechnungen'
    | '/sitemap.xml'
    | '/statistiken'
    | '/telefon'
    | '/tourenplanung'
    | '/verbindungen'
    | '/versicherungen'
    | '/warnungen'
    | '/wartung'
    | '/api/chat'
    | '/ki-assistent/$threadId'
    | '/ki-assistent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/aktions-center'
    | '/aktivitaeten'
    | '/auftraege'
    | '/berichte'
    | '/buchhaltung'
    | '/control-center'
    | '/dialysezentren'
    | '/dokumente'
    | '/einstellungen'
    | '/fahrer'
    | '/fahrzeuge'
    | '/insights'
    | '/krankenhaeuser'
    | '/kunden'
    | '/leasing'
    | '/live-gps'
    | '/patienten'
    | '/pflegeheime'
    | '/posteingang'
    | '/prognosen'
    | '/rechnungen'
    | '/sitemap.xml'
    | '/statistiken'
    | '/telefon'
    | '/tourenplanung'
    | '/verbindungen'
    | '/versicherungen'
    | '/warnungen'
    | '/wartung'
    | '/api/chat'
    | '/ki-assistent/$threadId'
    | '/ki-assistent'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/aktions-center'
    | '/aktivitaeten'
    | '/auftraege'
    | '/berichte'
    | '/buchhaltung'
    | '/control-center'
    | '/dialysezentren'
    | '/dokumente'
    | '/einstellungen'
    | '/fahrer'
    | '/fahrzeuge'
    | '/insights'
    | '/ki-assistent'
    | '/krankenhaeuser'
    | '/kunden'
    | '/leasing'
    | '/live-gps'
    | '/patienten'
    | '/pflegeheime'
    | '/posteingang'
    | '/prognosen'
    | '/rechnungen'
    | '/sitemap.xml'
    | '/statistiken'
    | '/telefon'
    | '/tourenplanung'
    | '/verbindungen'
    | '/versicherungen'
    | '/warnungen'
    | '/wartung'
    | '/api/chat'
    | '/ki-assistent/$threadId'
    | '/ki-assistent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AktionsCenterRoute: typeof AktionsCenterRoute
  AktivitaetenRoute: typeof AktivitaetenRoute
  AuftraegeRoute: typeof AuftraegeRoute
  BerichteRoute: typeof BerichteRoute
  BuchhaltungRoute: typeof BuchhaltungRoute
  ControlCenterRoute: typeof ControlCenterRoute
  DialysezentrenRoute: typeof DialysezentrenRoute
  DokumenteRoute: typeof DokumenteRoute
  EinstellungenRoute: typeof EinstellungenRoute
  FahrerRoute: typeof FahrerRoute
  FahrzeugeRoute: typeof FahrzeugeRoute
  InsightsRoute: typeof InsightsRoute
  KiAssistentRoute: typeof KiAssistentRouteWithChildren
  KrankenhaeuserRoute: typeof KrankenhaeuserRoute
  KundenRoute: typeof KundenRoute
  LeasingRoute: typeof LeasingRoute
  LiveGpsRoute: typeof LiveGpsRoute
  PatientenRoute: typeof PatientenRoute
  PflegeheimeRoute: typeof PflegeheimeRoute
  PosteingangRoute: typeof PosteingangRoute
  PrognosenRoute: typeof PrognosenRoute
  RechnungenRoute: typeof RechnungenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatistikenRoute: typeof StatistikenRoute
  TelefonRoute: typeof TelefonRoute
  TourenplanungRoute: typeof TourenplanungRoute
  VerbindungenRoute: typeof VerbindungenRoute
  VersicherungenRoute: typeof VersicherungenRoute
  WarnungenRoute: typeof WarnungenRoute
  WartungRoute: typeof WartungRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wartung': {
      id: '/wartung'
      path: '/wartung'
      fullPath: '/wartung'
      preLoaderRoute: typeof WartungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warnungen': {
      id: '/warnungen'
      path: '/warnungen'
      fullPath: '/warnungen'
      preLoaderRoute: typeof WarnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versicherungen': {
      id: '/versicherungen'
      path: '/versicherungen'
      fullPath: '/versicherungen'
      preLoaderRoute: typeof VersicherungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verbindungen': {
      id: '/verbindungen'
      path: '/verbindungen'
      fullPath: '/verbindungen'
      preLoaderRoute: typeof VerbindungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourenplanung': {
      id: '/tourenplanung'
      path: '/tourenplanung'
      fullPath: '/tourenplanung'
      preLoaderRoute: typeof TourenplanungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telefon': {
      id: '/telefon'
      path: '/telefon'
      fullPath: '/telefon'
      preLoaderRoute: typeof TelefonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiken': {
      id: '/statistiken'
      path: '/statistiken'
      fullPath: '/statistiken'
      preLoaderRoute: typeof StatistikenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechnungen': {
      id: '/rechnungen'
      path: '/rechnungen'
      fullPath: '/rechnungen'
      preLoaderRoute: typeof RechnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prognosen': {
      id: '/prognosen'
      path: '/prognosen'
      fullPath: '/prognosen'
      preLoaderRoute: typeof PrognosenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posteingang': {
      id: '/posteingang'
      path: '/posteingang'
      fullPath: '/posteingang'
      preLoaderRoute: typeof PosteingangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pflegeheime': {
      id: '/pflegeheime'
      path: '/pflegeheime'
      fullPath: '/pflegeheime'
      preLoaderRoute: typeof PflegeheimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patienten': {
      id: '/patienten'
      path: '/patienten'
      fullPath: '/patienten'
      preLoaderRoute: typeof PatientenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-gps': {
      id: '/live-gps'
      path: '/live-gps'
      fullPath: '/live-gps'
      preLoaderRoute: typeof LiveGpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leasing': {
      id: '/leasing'
      path: '/leasing'
      fullPath: '/leasing'
      preLoaderRoute: typeof LeasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden': {
      id: '/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof KundenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krankenhaeuser': {
      id: '/krankenhaeuser'
      path: '/krankenhaeuser'
      fullPath: '/krankenhaeuser'
      preLoaderRoute: typeof KrankenhaeuserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ki-assistent': {
      id: '/ki-assistent'
      path: '/ki-assistent'
      fullPath: '/ki-assistent'
      preLoaderRoute: typeof KiAssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeuge': {
      id: '/fahrzeuge'
      path: '/fahrzeuge'
      fullPath: '/fahrzeuge'
      preLoaderRoute: typeof FahrzeugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrer': {
      id: '/fahrer'
      path: '/fahrer'
      fullPath: '/fahrer'
      preLoaderRoute: typeof FahrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumente': {
      id: '/dokumente'
      path: '/dokumente'
      fullPath: '/dokumente'
      preLoaderRoute: typeof DokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialysezentren': {
      id: '/dialysezentren'
      path: '/dialysezentren'
      fullPath: '/dialysezentren'
      preLoaderRoute: typeof DialysezentrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center': {
      id: '/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof ControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchhaltung': {
      id: '/buchhaltung'
      path: '/buchhaltung'
      fullPath: '/buchhaltung'
      preLoaderRoute: typeof BuchhaltungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berichte': {
      id: '/berichte'
      path: '/berichte'
      fullPath: '/berichte'
      preLoaderRoute: typeof BerichteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auftraege': {
      id: '/auftraege'
      path: '/auftraege'
      fullPath: '/auftraege'
      preLoaderRoute: typeof AuftraegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivitaeten': {
      id: '/aktivitaeten'
      path: '/aktivitaeten'
      fullPath: '/aktivitaeten'
      preLoaderRoute: typeof AktivitaetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktions-center': {
      id: '/aktions-center'
      path: '/aktions-center'
      fullPath: '/aktions-center'
      preLoaderRoute: typeof AktionsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ki-assistent/': {
      id: '/ki-assistent/'
      path: '/'
      fullPath: '/ki-assistent/'
      preLoaderRoute: typeof KiAssistentIndexRouteImport
      parentRoute: typeof KiAssistentRoute
    }
    '/ki-assistent/$threadId': {
      id: '/ki-assistent/$threadId'
      path: '/$threadId'
      fullPath: '/ki-assistent/$threadId'
      preLoaderRoute: typeof KiAssistentThreadIdRouteImport
      parentRoute: typeof KiAssistentRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KiAssistentRouteChildren {
  KiAssistentThreadIdRoute: typeof KiAssistentThreadIdRoute
  KiAssistentIndexRoute: typeof KiAssistentIndexRoute
}

const KiAssistentRouteChildren: KiAssistentRouteChildren = {
  KiAssistentThreadIdRoute: KiAssistentThreadIdRoute,
  KiAssistentIndexRoute: KiAssistentIndexRoute,
}

const KiAssistentRouteWithChildren = KiAssistentRoute._addFileChildren(
  KiAssistentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AktionsCenterRoute: AktionsCenterRoute,
  AktivitaetenRoute: AktivitaetenRoute,
  AuftraegeRoute: AuftraegeRoute,
  BerichteRoute: BerichteRoute,
  BuchhaltungRoute: BuchhaltungRoute,
  ControlCenterRoute: ControlCenterRoute,
  DialysezentrenRoute: DialysezentrenRoute,
  DokumenteRoute: DokumenteRoute,
  EinstellungenRoute: EinstellungenRoute,
  FahrerRoute: FahrerRoute,
  FahrzeugeRoute: FahrzeugeRoute,
  InsightsRoute: InsightsRoute,
  KiAssistentRoute: KiAssistentRouteWithChildren,
  KrankenhaeuserRoute: KrankenhaeuserRoute,
  KundenRoute: KundenRoute,
  LeasingRoute: LeasingRoute,
  LiveGpsRoute: LiveGpsRoute,
  PatientenRoute: PatientenRoute,
  PflegeheimeRoute: PflegeheimeRoute,
  PosteingangRoute: PosteingangRoute,
  PrognosenRoute: PrognosenRoute,
  RechnungenRoute: RechnungenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatistikenRoute: StatistikenRoute,
  TelefonRoute: TelefonRoute,
  TourenplanungRoute: TourenplanungRoute,
  VerbindungenRoute: VerbindungenRoute,
  VersicherungenRoute: VersicherungenRoute,
  WarnungenRoute: WarnungenRoute,
  WartungRoute: WartungRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
